# -*- coding: utf-8 -*-
"""SpeechBrain_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xWtTTFzwwHVikUnrEcWsYg_M5TgZz2dh
"""

!pip install speechbrain torch sounddevice soundfile librosa matplotlib

import librosa
import soundfile as sf

filename = "/content/Recording (20).m4a"   # replace with your uploaded file name

# Load and resample to 16 kHz mono
y, sr = librosa.load(filename, sr=16000, mono=True)

# Optionally save as wav for SpeechBrain
sf.write("my_voice.wav", y, sr)
print("Saved")

import wave
import os
import random
from speechbrain.pretrained.interfaces import foreign_class
from IPython.display import Audio
classifier = foreign_class(source="speechbrain/emotion-recognition-wav2vec2-IEMOCAP", pymodule_file="custom_interface.py", classname="CustomEncoderWav2vec2Classifier")
def emotion_recognition(file_name):

    with wave.open(file_name, 'rb') as wav_file:
        frame_rate = wav_file.getframerate()
        channels = wav_file.getnchannels()
        sample_width = wav_file.getsampwidth()
        frame_count = wav_file.getnframes()
        segment_length = 10 * frame_rate

        for i in range(0, frame_count, segment_length):
            temp_file_name = 'temp.wav'

            with wave.open(temp_file_name, 'wb') as new_wav_file:
                new_wav_file.setframerate(frame_rate)
                new_wav_file.setnchannels(channels)
                new_wav_file.setsampwidth(sample_width)
                segment = wav_file.readframes(segment_length)
                new_wav_file.writeframes(segment)

            out_prob, score, index, text_lab = classifier.classify_file(temp_file_name)
            return text_lab[0]

emotion_recognition("my_voice.wav")

import librosa
import soundfile as sf

filename = "/content/Recording (21).m4a"   # replace with your uploaded file name

# Load and resample to 16 kHz mono
y, sr = librosa.load(filename, sr=16000, mono=True)

# Optionally save as wav for SpeechBrain
sf.write("my_voice2.wav", y, sr)
print("Saved")

emotion_recognition("my_voice2.wav")

